### ISSUE TITLE
App logs for Ruby app

### ISSUE THREAD

**Issue by Akirtovskis** [ledokku/ledokku#109]
After deploying ruby heroku starter I realised that ruby logs are different from node js logs. 

So we should create different log parser  for Ruby: 
`server/src/lib/dokku/apps/logs.ts` 

For now it's just Ruby, but we need to check other languages too and potentially create issues.

**Comment by pradel** [comment]
@Akirtovskis do you have an example of some ruby logs? I guess the logs output depends of the logger you utilise not the language, so we will have to find a generic way to parse the logs probably...

**Comment by Akirtovskis** [comment]
@pradel there you go. This is the same command and outputs vary by quite a bit :) 

RUBY

<img width="812" alt="Screenshot 2020-08-04 at 23 11 37" src="https://user-images.githubusercontent.com/25903618/89340114-e64e6000-d6a7-11ea-9d5a-44750387ab20.png">

NODE 

<img width="500" alt="Screenshot 2020-08-04 at 23 12 21" src="https://user-images.githubusercontent.com/25903618/89340179-01b96b00-d6a8-11ea-8f66-6085625237c6.png">

**Comment by Akirtovskis** [comment]
GO logs preview 

![image](https://user-images.githubusercontent.com/25903618/89655532-ee3e1800-d8d2-11ea-8bb7-ed4da40b5692.png)

**Comment by Akirtovskis** [comment]
@Akirtovskis parse logs - one new log per line.
