### ISSUE TITLE
Prisma not found 

### ISSUE THREAD

**Issue by nbpalomino** [ledokku/ledokku#125]
Cannot install Ledokku 0.0.1 from Docker Hub, it says Manifest unknown. So im using latest. 

Also when finally run * dokku tags:deploy ledokku* it fails with image below... 

Any ideas? Thanks in advance...

![image](https://user-images.githubusercontent.com/1450270/93275740-53fbaa80-f783-11ea-9a42-3e879074e6c6.png)

**Comment by pradel** [comment]
> Cannot install Ledokku 0.0.1 from Docker Hub, it says Manifest unknown. So im using latest.

Yeah we didn't reach the first alpha release yet that's why there are no tags for now.

The issue is now solved, can you try to pull the latest tag again?
