### ISSUE TITLE
Synchronise existing dokku server

### ISSUE THREAD

**Issue by pradel** [ledokku/ledokku#143]
# Feature request

When I install ledokku I want the db to be populated with existing apps and dbs already running

**Comment by ScottGuthart** [comment]
Is there a way to do this manually in the meantime?

**Comment by pradel** [comment]
@ScottGuthart the only way to do it, for now, would be to insert the app into the database manually.

**Comment by pradel** [comment]
@ScottGuthart if you install version 0.1.0 it should now synchronise the existing dokku services, let me know if you face any issue :)

**Comment by ScottGuthart** [comment]
> @ScottGuthart if you install version 0.1.0 it should now synchronise the existing dokku services, let me know if you face any issue :)

Awesome! That was quick! Is there a way for me to upgrade an existing installation or should I just reinstall Ledokku?

**Comment by pradel** [comment]
@ScottGuthart I think that running the following should work
```
docker pull ledokku/ledokku:0.1.0
docker tag ledokku/ledokku:0.1.0 dokku/ledokku:0.1.0
dokku tags:deploy ledokku 0.1.0
```

**Comment by ScottGuthart** [comment]
Looks like it worked!

It does list the Ledokku app + dbs which may not be a big deal.

**Comment by pradel** [comment]
> It does list the Ledokku app + dbs which may not be a big deal.

Good point, while developing locally I didn't have this problem. Will be fixed in the next version 👍
