### ISSUE TITLE
Display deployment instructions on the docker hub page

### ISSUE THREAD

**Issue by pradel** [ledokku/ledokku#149]
# Feature request

Display deployment instructions on the docker hub page (or link to the documentation).

https://hub.docker.com/r/ledokku/ledokku

**Comment by ScottGuthart** [comment]
It looks like this is also coming for the docs as the last step in Installation says "Follow the next guide to properly setup up your domain name and deploy your first app."

Are there instructions or a link to corresponding dokku docs that can be followed in the meantime for those that have completed the steps in the instructions? 

I installed a fresh dokku instance following the docs and wondering what to do next.

**Comment by pradel** [comment]
@ScottGuthart good point, we will update the docs to make it more clear as the next step is not ready yet, in the between here is the link that explains how to deploy an application :) http://dokku.viewdocs.io/dokku/deployment/application-deployment/

**Comment by ScottGuthart** [comment]
@pradel -- great, thanks! That's what I followed and it worked great, as long as I was careful to match up the name of the app with the same name I gave It with Ledokku. 

Do you happen to have a suggestion for domain setup also? This is still not working on my end after enabling virtual host naming as suggested in the instructions.

**Comment by pradel** [comment]
> Do you happen to have a suggestion for domain setup also? This is still not working on my end after enabling virtual host naming as suggested in the instructions.

Do you want to enable a custom domain for your deployed app or for the ledokku admin? If you are trying to rename it for the ledokku admin you might have to redirect the port 4000 to 80.

Just pointing my domain DNS to my server IP and checking that domains where configured properly worked for me. You can see your domain configuration using `dokku domains:report`.

**Comment by ScottGuthart** [comment]
> > Do you happen to have a suggestion for domain setup also? This is still not working on my end after enabling virtual host naming as suggested in the instructions.
> 
> Do you want to enable a custom domain for your deployed app or for the ledokku admin? If you are trying to rename it for the ledokku admin you might have to redirect the port 4000 to 80.
> 
> Just pointing my domain DNS to my server IP and checking that domains where configured properly worked for me. You can see your domain configuration using `dokku domains:report`.

I am able to access Ledokku via port 4000 at the root domain but I cannot access the app I deployed. This could be an issue on my end, my app is listening at port 5000 and I'm not sure if there's another step I need to take to expose it.

**Comment by pradel** [comment]
If you are using port 5000 you might have to expose it in order to be able to access it `sudo ufw allow 5000`

**Comment by ScottGuthart** [comment]
> If you are using port 5000 you might have to expose it in order to be able to access it `sudo ufw allow 5000`

No luck with this unfortunately, my reading of the [Dokku docs](http://dokku.viewdocs.io/dokku/networking/port-management/#applications-not-using-expose) gives me the impression that apps deployed to port 5000 should work by default.

**Comment by pradel** [comment]
I can see that you are using the domain `dokku.me`, you probably want to replace it with your own domain.

Also stupid question but did you check your app logs to see that it was properly started (without errors)?

What is the output of `dokku proxy:ports myapp `?

**Comment by ScottGuthart** [comment]
> I can see that you are using the domain `dokku.me`, you probably want to replace it with your own domain.
> 
> Also stupid question but did you check your app logs to see that it was properly started (without errors)?
> 
> What is the output of `dokku proxy:ports myapp `?

I do have it setup to a custom domain, I just substituted my custom domain out before posting.

```shell
root@ledokku:~# dokku proxy:ports myapp
-----> Port mappings for myapp
    -----> scheme  host port  container port
    http           80         5000
```

Here are my app logs, it looks to have started successfully and listening on port 5000.
```shell
2020-10-04T22:40:14.573725485Z app[web.1]: [2020-10-04 22:40:14 +0000] [155] [INFO] Starting gunicorn 20.0.4
2020-10-04T22:40:14.581249228Z app[web.1]: [2020-10-04 22:40:14 +0000] [155] [INFO] Listening at: http://0.0.0.0:5000 (155)
2020-10-04T22:40:14.581274460Z app[web.1]: [2020-10-04 22:40:14 +0000] [155] [INFO] Using worker: sync
2020-10-04T22:40:14.584636880Z app[web.1]: [2020-10-04 22:40:14 +0000] [158] [INFO] Booting worker with pid: 158
2020-10-04T22:40:18.660022229Z app[web.1]: [2020-10-04 22:40:18,659] INFO in __init__: Flaskapp startup
2020-10-04T22:40:18.780455387Z app[web.1]: [2020-10-04 22:40:18,779] INFO in __init__: Flaskapp startup
```

This is a web pack deploy. Maybe I need to use a dockerfile with the expose command?

**Comment by pradel** [comment]
The herokuish deploy should work just fine. Like this I don't see anything wrong with your config..

As it is related to the dokku behavior you will probably have more luck asking the dokku community indeed :)

**Comment by ScottGuthart** [comment]
> > I can see that you are using the domain `dokku.me`, you probably want to replace it with your own domain.
> > Also stupid question but did you check your app logs to see that it was properly started (without errors)?
> > What is the output of `dokku proxy:ports myapp `?
> 
> I do have it setup to a custom domain, I just substituted my custom domain out before posting.
> 
> ```shell
> root@ledokku:~# dokku proxy:ports myapp
> -----> Port mappings for myapp
>     -----> scheme  host port  container port
>     http           80         5000
> ```
> 
> Here are my app logs, it looks to have started successfully and listening on port 5000.
> 
> ```shell
> 2020-10-04T22:40:14.573725485Z app[web.1]: [2020-10-04 22:40:14 +0000] [155] [INFO] Starting gunicorn 20.0.4
> 2020-10-04T22:40:14.581249228Z app[web.1]: [2020-10-04 22:40:14 +0000] [155] [INFO] Listening at: http://0.0.0.0:5000 (155)
> 2020-10-04T22:40:14.581274460Z app[web.1]: [2020-10-04 22:40:14 +0000] [155] [INFO] Using worker: sync
> 2020-10-04T22:40:14.584636880Z app[web.1]: [2020-10-04 22:40:14 +0000] [158] [INFO] Booting worker with pid: 158
> 2020-10-04T22:40:18.660022229Z app[web.1]: [2020-10-04 22:40:18,659] INFO in __init__: Flaskapp startup
> 2020-10-04T22:40:18.780455387Z app[web.1]: [2020-10-04 22:40:18,779] INFO in __init__: Flaskapp startup
> ```
> 
> This is a web pack deploy. Maybe I need to use a dockerfile with the expose command?



> The herokuish deploy should work just fine. Like this I don't see anything wrong with your config..
> 
> As it is related to the dokku behavior you will probably have more luck asking the dokku community indeed :)

Ok, will do! The app is beautiful @pradel, thank you for your work! Looking forward to seeing it develop.

**Comment by pradel** [comment]
Thanks for the kind words!

**Comment by pradel** [comment]
@Akirtovskis closing this one as I updated the docker page https://hub.docker.com/r/ledokku/ledokku
