### ISSUE TITLE
Use new headless ui menu dropdown component for the top right profile menu

### ISSUE THREAD

**Issue by pradel** [ledokku/ledokku#167]
# Feature request

See https://github.com/tailwindlabs/headlessui/tree/develop/packages/%40headlessui-react#menu-button-dropdown

**Comment by Akirtovskis** [comment]
This could probably be used for linking/unlinking dropdown menus as well.

**Comment by Akirtovskis** [comment]
As discussed offline, listbox will be better for link/unlink use case, new issue for this :  https://github.com/ledokku/ledokku/issues/168
