### ISSUE TITLE
App fails to deploy, SIGABRT

### ISSUE THREAD

**Issue by railto** [ledokku/ledokku#188]
# Bug report

Following error is being thrown when trying to deploy the app for the first time
```shell
/usr/local/bin/node[29]: ../src/node_http_parser_impl.h:529:static void node::{anonymous}::Parser::Initialize(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[3]->IsInt32()' failed.
       error Command failed with signal "SIGABRT".
```

## To Reproduce

Follow the [installation instructions](https://www.ledokku.com/docs/installation/), error is thrown at the `dokku tags:deploy ledokku 0.2.0` stage

## Expected behavior

App should deploy

## Screenshots

<img width="1650" alt="Screenshot 2020-10-18 at 23 11 31" src="https://user-images.githubusercontent.com/6123557/96387039-4cbb2880-1197-11eb-93ac-7b36d249ff0a.png">

## System information

- Version of dokku: 0.21.4
- Version of ledokku: 0.2.0

**Comment by pradel** [comment]
@railto Thanks for reporting the issue, it has been fixed in `v0.2.1`!
