### ISSUE TITLE
Authentication & Security Model

### ISSUE THREAD

**Issue by kidGodzilla** [ledokku/ledokku#223]
Can you describe your authentication & security model somewhere?

How is ACL implemented?

From what I can tell:

1. You install Ledokku over Dokku, granting the ledokku user unlimited access to your Dokku instance.
2. Anyone can create a Ledokku account, as long as they have a GitHub username to SSO w/ GitHub.
3. Everyone who has access to GitHub and discovers the Ledokku service is running can read a list of apps and read all of their environment variables, and create an unlimited number of empty databases and apps.

**Comment by pradel** [comment]
@kidGodzilla we will add it to the documentation, that's a good question.

> You install Ledokku over Dokku, granting the ledokku user unlimited access to your Dokku instance.

Indeed, if you want to be able to manage your apps and dbs imho there is no other way.

> Anyone can create a Ledokku account, as long as they have a GitHub username to SSO w/ GitHub.

This is true, but in the current version of the project **we only allow one user to signup**, meaning that if another person tries to login via Github on your instance he will get rejected. Later we plan to let you invite more users and maybe do some team/role management for the apps.

> Everyone who has access to GitHub and discovers the Ledokku service is running can read a list of apps and read all of their environment variables, and create an unlimited number of empty databases and apps.

As the API is secured via JWT, only a logged in user can actually do this. And as said earlier only one user is allowed per server for now to mitigate this risk :)

Regarding the security itself, the HTTP and WS connections are secured using a JWT. The JWT secret is generated randomly when you install ledokku on your server.

**Comment by kidGodzilla** [comment]
Got it! **we only allow one user to signup** was the missing piece

**Comment by pradel** [comment]
We will write some documentation to make it clear, thanks for raising this point 👍
