### ISSUE TITLE
0.3.2 tag is not on Docker Hub, so install fails

### ISSUE THREAD

**Issue by sardaukar** [ledokku/ledokku#226]
# Bug report

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository.

## System information

- Version of dokku: [e.g. 0.21.4]
- Version of ledokku: [e.g. 0.0.1]

**Comment by pradel** [comment]
@sardaukar you are right looks like there was a problem during the previous release. I just released a new version and the tag was created properly on docker, if you retry with v0.3.3 it should work. Thanks for reporting!
