### ISSUE TITLE
Ledokku fails to load when it is served over HTTPS

### ISSUE THREAD

**Issue by zedalaye** [ledokku/ledokku#255]
# Bug report

## Describe the bug

I installed ledokku on my dokku instance behind HAProxy (it terminates SSL connections and handles LetsEncrypt certificates), when I try to access the ledokku page, I get this error into the JS console :

`client.ts:557 Mixed Content: The page at 'https://ledokku.xxxxx.xx/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://ledokku.xxxxx.xx/graphql'. This request has been blocked; this endpoint must be available over WSS.`

## To Reproduce

Not sure how to safely reproduce this error.

Because I cannot run docker commands on my server, I wrapped ledokku using dokku's "Dockerfile deployment", I created a simple Dockerfile containing :

```Dockerfile
FROM ledokku/ledokku:0.4.0

# Add custom nginx.conf template for Dokku to use
ADD nginx.conf.sigil /usr/src/app/server
```

I used the dokku v0.21.4 nginx.conf template where I modified the proxy related configuration values to:

```nginx.conf
...
    proxy_pass  http://{{ $.APP }}-{{ $upstream_port }};
    proxy_http_version 1.1;
    proxy_read_timeout {{ $.PROXY_READ_TIMEOUT }};
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
    proxy_set_header X-Forwarded-For $http_x_forwarded_for;
    proxy_set_header X-Forwarded-Port $http_x_forwarded_port;
    proxy_set_header X-Request-Start $msec;
...
```

Using this trick, I deploy ledokku by running `git push`

## Expected behavior

Ledokku page is displayed

## System information

- Version of dokku: [e.g. 0.21.4]
- Version of ledokku: [e.g. 0.4.0]

**Comment by pradel** [comment]
@zedalaye thanks for opening the issue, should be solved in [v0.5.0](https://github.com/ledokku/ledokku/releases/tag/v0.5.0) 🎉

**Comment by zedalaye** [comment]
Deployed ! It works

But now I have to allow ledokku to access my dokku instance through my bastion... How safe could this be ?

**Comment by pradel** [comment]
ledokku needs ssh to execute dokku commands on your server, it should be safe as the API is protected using JWT. We also check all the inputs coming from the user before executing any ssh command to avoid bad commands to be run.
