### ISSUE TITLE
App/Db header layout issue

### ISSUE THREAD

**Issue by Akirtovskis** [ledokku/ledokku#267]
# Bug report

Header not aligned with Ledokku title at the top

Main view is properly aligned, but app / db view is not

## To Reproduce

Run the app, compare main view vs individual app/db view

## Expected behavior

Should be aligned

## Screenshots

![image](https://user-images.githubusercontent.com/25903618/107330361-1f81e580-6aba-11eb-9dfe-608d90ffb1f9.png)

**VS**

![image](https://user-images.githubusercontent.com/25903618/107330480-47714900-6aba-11eb-91df-11422b84acfc.png)

## System information

- Version of dokku: [e.g. 0.23.0]
- Version of ledokku: [e.g. 0.5.0]

**Comment by Akirtovskis** [comment]
@pradel if this spacing was intended, let's close this one.

**Comment by pradel** [comment]
@Akirtovskis will be fixed once we use Chakra in all the views :D

**Comment by Akirtovskis** [comment]
@pradel oh ok, I will take care of migrating these views then.
