### ISSUE TITLE
Fix toast messages on db creation

### ISSUE THREAD

**Issue by Akirtovskis** [ledokku/ledokku#302]
# Bug report

## To Reproduce

Create db and see multiple toast messages appearing at the same time

## Expected behavior

One toast appears

## System information

- Version of dokku: [e.g. 0.21.4]
- Version of ledokku: [e.g. 0.0.1]

**Comment by pradel** [comment]
I did it multiple time today but didn't manage to reproduce it. Maybe it's gone?

**Comment by Akirtovskis** [comment]
Yeah, let's close this one.
