### ISSUE TITLE
github login redirecting to 404 page

### ISSUE THREAD

**Issue by dmo9** [ledokku/ledokku#413]
# Bug report

## Describe the bug
I've logged into ledokku before, but now when I return I'm presented with "login with github" button. Upon clicking this, I'm redirected to a github 404 page with no way of logging into ledokku. Clearing cookies makes no difference.

## Screenshots

![ledokku](https://user-images.githubusercontent.com/28460065/161310674-634402a0-db48-457f-9cf6-04b8fe09e0aa.PNG)
![404](https://user-images.githubusercontent.com/28460065/161310678-ffd721e2-ce7d-4bf9-8199-4d7a7a7340d2.PNG)

## System information

- Version of dokku: 0.27.0
- Version of ledokku: latest

**Comment by dmo9** [comment]
Solved - I somehow had removed the integration from my github account

**Comment by nkCreation** [comment]
Hello. How did you resolve this ? I've encoutered this problem since I have enable HTTPS
thank you :)

**Comment by dmo9** [comment]
> Hello. How did you resolve this ? I've encoutered this problem since I have enable HTTPS thank you :)

I had accidentally removed the integration from my github account so I added it back. I think I uninstalled and then reinstalled ledokku

**Comment by oflynned** [comment]
+1 I have not changed any integration settings and had to do a full reinstall of Ledokku to login
